/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BooksBookIdImport } from './routes/books/$bookId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const BooksIndexLazyImport = createFileRoute('/books/')()
const AuthIndexLazyImport = createFileRoute('/auth/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const BooksIndexLazyRoute = BooksIndexLazyImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/books/index.lazy').then((d) => d.Route))

const AuthIndexLazyRoute = AuthIndexLazyImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/auth/index.lazy').then((d) => d.Route))

const BooksBookIdRoute = BooksBookIdImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/auth': typeof AuthIndexLazyRoute
  '/books': typeof BooksIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/auth': typeof AuthIndexLazyRoute
  '/books': typeof BooksIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/auth/': typeof AuthIndexLazyRoute
  '/books/': typeof BooksIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/books/$bookId' | '/auth' | '/books'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/books/$bookId' | '/auth' | '/books'
  id: '__root__' | '/' | '/books/$bookId' | '/auth/' | '/books/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  AuthIndexLazyRoute: typeof AuthIndexLazyRoute
  BooksIndexLazyRoute: typeof BooksIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  AuthIndexLazyRoute: AuthIndexLazyRoute,
  BooksIndexLazyRoute: BooksIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/books/$bookId",
        "/auth/",
        "/books/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/books/$bookId": {
      "filePath": "books/$bookId.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.lazy.tsx"
    },
    "/books/": {
      "filePath": "books/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
